### ISSUE TITLE
Why wait for new version to start on darwin?

### ISSUE THREAD

**Issue by Korijn** [phfaist/updater4pyi#2]
I was just reading your code, trying to understand the update process on OS X / Linux, can you explain the following lines?

https://github.com/phfaist/updater4pyi/blob/master/updater4pyi/upd_core.py#L648-L650

``` python
    subprocess.Popen("while ps -p %d >/dev/null; do sleep 1; done; ( %s & )"
        %(this_pid, exe_cmd),
        shell=True)
```

**Comment by phfaist** [comment]
Thanks for your interest!

I think those lines were mostly so that the old version of the program could free up any resources before running the new version. Say, if the old program updates its configuration file upon exit, you'd want the new version of the program to pick up the updated file.

I'm no longer sure if there was a stronger reason. There might have been also an issue if the program executable was located on some non-unix-like filesystem (sshfs, ...).

**Comment by Korijn** [comment]
I'm considering implementing something similar (although slimmed down) and your code is a very useful reference for me. :)

Do you still use this library? Would you consider it to be "well supported" and/or "stable"?

**Comment by phfaist** [comment]
Happy to be useful :)

I wrote the code in a rather short period of time, I tried to be careful, tested it on various platforms at the time, and haven't really modified it much since and haven't noticed any major catastrophes. I'm using it for my own project [bibolamazi](https://github.com/phfaist/bibolamazi). That's pretty much as far as I it goes about being "well supported and/or stable". As any open source project, you know, no guarantees.

Of course if you're willing to contribute code back eg. in the form of an update source or interface you're welcome to send me a pull request :)

**Comment by Korijn** [comment]
Well, right now my plan is to create an application that installs and updates within the appdata directories of Windows, so I'm thinking it'll be very similar to Google Chrome. I have to operate this within corporate networks littered with outdated tech and complete lock-down, so I'm carefully considering all options. :)

I'm completely clueless about OS X at this point though, I haven't had time to investigate how things work in Apple country. Is there an analog to the appdata directory? Or some other place that is garantueed to be writable? It's relevant because SOME of our end-users operate at home on their laptops/macbooks.

**Comment by phfaist** [comment]
I see, good luck :) I'm really not quite sure actually about these directories any more because it has been some time I haven't looked at that, sorry.

**Comment by wettenhj** [comment]
I've been watching this project quietly with interest.  I use Mac OS X regularly, so perhaps I can answer the question about the OS X analog to the appdata directory, and comment on the Google Chrome example.

On PyPi, there is a module called appdirs which helps with this: https://pypi.python.org/pypi/appdirs/

The closest analog to Windows' appdata directory is probably `~/Library/Application Support/`

However other directories within `~/Library/` are also used for storing user-specific application data, for example `~/Library/Google/GoogleSoftwareUpdate/` and `~/Library/Logs/GoogleSoftwareUpdateAgent.log`.

Google Chrome on Mac OS X provides a drag-and-drop installer, i.e. you drag Google Chrome.app from a downloaded disk image (DMG) into your Mac's /Applications/ folder (or somewhere else if you don't have permission to put it there).  Privilege elevation is required to copy it into /Applications/, but then once it's there, it is writeable by whoever installed it, so Chrome or GoogleSoftwareUpdateAgent can install updates into /Applications/Google Chrome.app/Contents/Versions/ and update the current version number in  /Applications/Google Chrome.app/Contents/Info.plist without requiring further privilege elevation.

**Comment by Korijn** [comment]
@wettenhj Thanks for your enlightening comments!

In our case, the privilege elevation is less of an issue on OS X since this is not an environment encountered in the corporate networks we support (it's mostly Windows XP unfortunately). When we deploy on OS X it will most likely be on someone's private MacBook.

This has been very informative. I'll make sure to leave updates in this thread when we start work on this project. Thanks @phfaist!
